// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://supznesgzmogxockjckg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1cHpuZXNnem1vZ3hvY2tqY2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzY0MjEsImV4cCI6MjA1NDI1MjQyMX0.VkQTduCP_8H5iaQ9tRIx7sAUJkgEuh8mKObF3lhDBaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);